--- 
kind: service
apiVersion: v1
metadata: 
  name: hellowordservice
spec: 
  selector: 
    app: hello-world
  ports:
    - protocol: "TCP"
    # Porta acessível dentro do cluster
      port: 8080
    # Porta para redirecionar dentro do cluster
      targetPort: 80
    # Porta acessível de fora do cluster
      nodePort: 30001
  type: LoadBalancer  



---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: hello-world
          ports:
            - containerPort: 80